<?php
return [
 'email_footer'                        => 'Ne répondez à aucun e-mail à cette adresse e-mail. Cet e-mail envoyé automatiquement par notre système. ',
 'login_message'                       => 'Veuillez vous connecter pour démarrer votre session',
 'text_forgot_password'                => 'Mdp oublié ?',
 'page_title_login'                    => 'Panneau de connexion',
 'page_title_forgot'                   => 'Mot de passe oublié',
 'forgot_message'                      => 'Entrez votre adresse e-mail pour demander le mot de passe',
 "forgot_text_try_again"               => "Essayez de vous reconnecter ?",
 'text_no_notification'                => "Vous avez 0 notification",
 'text_view_all_notification'          => 'Voir tout',
 'label_button_profile'                => "Profil",
 'filter_dialog_title'                 => 'Tri et filtre avancés',
 'there_is_no_option'                  => 'Il n\'y a pas de paramètre d\'options pour ce type d\'entrée',
 'no'                                  => 'Non.',

 'text_enter_the_password'             => 'Entrez votre mot de passe pour récupérer votre session',
 'text_or_sign_in'                     => 'Ou connectez-vous en tant qu utilisateur différent',
 'text_default_add_new_module'         => 'Ajouter un nouveau :module',
 'text_default_list_module'            => 'Liste :module',
 'text_default_help_password'          => 'Minimum 5 caractères. Veuillez laisser vide si vous n avez pas changé le mot de passe.',
 'text_default_help_upload'            => 'Types de fichiers pris en charge : JPG, JPEG, PNG, GIF, BMP',
 'text_default_help_number'            => 'Vous ne pouvez entrer que le numéro',
 'text_default_help_email'             => 'Veuillez saisir une adresse e-mail valide',
 'text_default_help_text'              => 'Vous ne pouvez saisir que la lettre uniquement',
 'text_default_help_url'               => 'Veuillez saisir une URL valide',
 'text_dashboard'                      => 'Tableau de bord',
 'text_delete'                         => 'Supprimer',
 'text_prefix_option'                  => '** Veuillez sélectionner un',
 'text_loading'                        => 'Veuillez patienter chargement...',

 'message_after_logout'                => 'Merci, à plus tard !',
 'message_forgot_password'             => 'Nous avons envoyé un nouveau mot de passe à votre adresse e-mail, vérifiez votre boîte de réception ou votre spam !',

 'page_not_found'                      => 'Oups ! Page non trouvée',
 'page_not_found_text'                 => 'Nous ne pouvons pas rechercher la page que vous recherchez.',
 'page_not_found_tips'                 => '* Veuillez vous assurer que l URL est correcte<br/>
                 * Veuillez vous assurer que la mise en majuscule de la police est correcte car sensible à la casse<br/>
                 * Peut-être que la page que vous recherchez a été supprimée par l administrateur<br/>
                 * Vous pouvez revenir en arrière en cliquant sur le bouton Retour du navigateur<br/>',

 'log_try_view'                        => 'Essayez de voir les données :name sur :module',
 'log_try_edit'                        => 'Essayez de modifier les données :name à :module',
 'log_try_add'                         => 'Essayez d\'ajouter des données à :module',
 'log_try_add_save'                    => 'Essayez d\'ajouter les données :name data à :module',
 'log_try_delete'                      => 'Essayez de supprimer les données :name sur :module',
 'log_try_delete_selected'             => 'Essayez de supprimer la sélection à :module',
 'log_try_delete_image'                => 'Essayez de supprimer l\'image de :name data à :module',
 'log_try_update'                      => 'Essayez de mettre à jour les données :name sur :module',
 'log_add'                             => 'Ajouter de nouvelles données :nom à :module',
 'log_update'                          => 'Mettre à jour les données :nom à :module',
 'log_delete'                          => 'Supprimer les données :nom à :module',
 'log_delete_image'                    => 'Supprime l image de :name à :module',
 'log_login'                           => ':email par e-mail avec adresse IP :ip',
 'log_forgot'                          => 'Quelqu un avec IP :ip demande un mot de passe pour :email',
 'log_logout'                          => ':email Déconexion',

 'alert_delete_selected'               => 'Voulez-vous vraiment supprimer toutes les données sélectionnées ?',
 'alert_delete_selected_success'       => 'Supprimer le succès sélectionné !',
 'alert_bulk_action_button'            => 'Êtes-vous sûr de vouloir',
 'alert_action'                        => 'Vous avez :action réussi !',
 'alert_add_data_success'              => 'Les données ont été ajoutées !',
 'alert_add_data_failed'               => 'Échec de la sauvegarde des données !',
 'alert_update_data_success'           => 'Les données ont été mises à jour !',
 'alert_update_data_failed'            => 'Échec de la mise à jour des données',
 'alert_delete_data_success'           => 'Suppression des données réussie !',
 'alert_want_to_logout'                => 'Voulez-vous vous déconnecter ?',
 'alert_warning'                       => "Oups",
 'alert_danger'                        => 'Quelque chose s\'est mal passé ....',
 'alert_success'                       => 'Waouh, bon travail...',
 'alert_info'                          => 'Informations',
 'alert_primary'                       => 'Informations',
 'alert_session_expired'               => 'Votre session a expiré, veuillez vous reconnecter !',
 'alert_password_wrong'                => 'Désolé, votre mot de passe est erroné !',
 'alert_required'                      => 'Veuillez vous assurer de remplir correctement tous les champs obligatoires',
 'alert_error_ajax'                    => ' quelque chose s est mal passé, nous allons le réparer bientôt !',
 'alert_validation_error'              => 'Veuillez remplir correctement le formulaire : :error',
 'alert_select_a_data'                 => 'Veuillez sélectionner au moins une donnée !',

 'add_data_page_title'                 => 'Ajouter :module',
 'edit_data_page_title'                => 'Modifier :module',
 'detail_data_page_title'              => 'Détail :module',

 'default_module_description'          => 'Liste de données',

 'delete_description_confirm'          => "Vous ne pourrez pas récupérer les données de cet enregistrement !",
 'language_description_confirm'        => "Vous allez changer la langue de l interface!",
 'delete_title_confirm'                => "Êtes-vous sûr ?",

 'action_show_data'                    => 'Afficher les données',
 'action_add_data'                     => 'Ajouter des données',
 'action_delete_selected'              => 'Supprimer la sélection',

 'action_label'                        => 'Action',
 'action_detail_data'                  => 'Données détaillées',
 'action_edit_data'                    => 'Modifier les données',
 'action_delete_data'                  => 'Supprimer',

 'button_cancel'                       => 'Annuler',
 'button_add'                          => 'Ajouter des données',
 'button_edit'                         => 'Modifier les données',
 'button_back'                         => 'Retour',
 'button_save'                         => 'Enregistrer',
 'button_save_more'                    => 'Enregistrer et ajouter plus',
 'button_import'                       => 'Importer des données',
 'button_export'                       => 'Exporter les données',
 'button_filter'                       => 'Trier & Filtrer',
 'button_close'                        => 'Fermer',
 'button_submit'                       => 'Soumettre',
 'button_logout'                       => 'Déconnexion',
 'button_sign_in'                      => 'Connexion',
 'button_selected_action'              => 'Actions groupées',
 'button_download_file'                => 'Télécharger le fichier',
 'button_reset'                        => 'Réinitialiser',
 'button_add_to_table'                 => 'Ajouter au tableau',

 'export_dialog_title'                 => "Exporter les données",
 'export_dialog_filename'              => 'Nom du fichier',
 'export_dialog_help_filename'         => 'Vous pouvez renommer le nom du fichier selon vos souhaits',
 'export_dialog_maxdata'               => "Données max",
 'export_dialog_help_maxdata'          => 'Minimum 1 et maximum 100 000 lignes par session d exportation',
 'export_dialog_columns'               => 'Colonnes',
 'export_dialog_format_export'         => 'Formater l exportation',
 'export_dialog_show_advanced'         => 'Afficher l exportation avancée',
 'export_dialog_page_size'             => 'Taille de la page',
 'export_dialog_set_default'           => 'Définir comme taille de papier par défaut',
 'export_dialog_page_orientation'      => 'Orientation de la page',

 'import_page_title'                   => 'Importer des données :module',
 'dashboard_default_text'              => 'Bienvenue sur le tableau de bord de :appname',
 'form_back_to_list'                   => 'Retour aux données de la liste :module',
 'not_logged_in'                       => 'Vous n\'êtes pas connecté !',
 'menu_navigation'                     => "Navigation",
 'table_data_not_found'                => "Aucune donnée disponible",
 "notice_delete_file_upload"           => "* Si vous souhaitez télécharger un autre fichier, veuillez d'abord le supprimer.",
 "file_broken"                         => "Oups, on dirait que le fichier était cassé !. Cliquez sur Supprimer et re-télécharger.",

 'denied_access'                       => 'Désolé, vous n\'avez pas le privilège d\'accéder à cette zone !',
 'denied_update'                       => 'Désolé, vous n\'avez pas le privilège de mettre à jour les données !',
 'denied_create'                       => 'Désolé, vous n\'avez pas le privilège de créer les données !',
 'denied_delete'                       => 'Désolé, vous n\'avez pas le privilège de supprimer les données !',

 'user_image'                          => 'Image utilisateur',
 'en ligne'                            => 'En ligne',
 'controller_route_404'                => 'Contrôleur / Route introuvable',
 'home'                                => 'Accueil',
 'Notifications'                       => 'Notifications',
 'Privilèges'                          => 'Privilèges',
 'Privileges_Roles'                    => 'Rôles de privilèges',
 'Add_New_Privilege'                   => 'Ajouter un nouveau privilège',
 'List_Privilege'                      => 'Liste Privilège',
 'add_user'                            => 'Ajouter un utilisateur',
 'List_users'                          => 'Liste des utilisateurs',
 'Menu_Management'                     => 'Gestion des menus',
 'Add_New_Setting'                     => 'Ajouter un nouveau paramètre',
 'Add_New_Module'                      => 'Ajouter un nouveau module',
 'List_Module'                         => 'Liste des modules',
 'Add_New_Statistic'                   => 'Ajouter une nouvelle statistique',
 'List_Statistic'                      => 'Liste statistique',
 'Add_New_API'                         => 'Ajouter une nouvelle API',
 'API_Generator'                       => 'Générateur d API',
 'Statistic_Builder'                   => 'Constructeur Stats',
 'Module_Generator'                    => 'Générateur de modules',
 'paramètres'                          => 'Paramètres',
 'Users_Management'                    => 'Gestion des utilisateurs',
 'list_API'                            => 'Liste API (Documentation)',
 'Generate_Screet_Key'                 => 'Générer une clé secrète',
 'Add_New_Email'                       => 'Ajouter un nouvel e-mail',
 'List_Email_Template'                 => 'Liste des modèles d e-mails',
 'Email_Templates'                     => 'Modèles d e-mails',
 'Log_User_Access'                     => 'Log User Access',
 'SUPERADMIN'                          => 'SUPERADMIN',

 'click_here'                          => 'Cliquez ici',
 'selected'                            => 'Select',

 /*
  * this is for html direction to use in html and css classes like :
  * pull-left , pull-right , text-right ...
  * to make it easy to use the the view for rtl langs .
  * unless your language use right-to-left direction , you should keep it as it is :
  */
 'right'                               => 'right',
 'left'                                => 'left',
 'all_rights_reserved'                 => 'Tous droits réservés',
 'copyright'                           => 'Copyright',
 'powered_by'                          => 'Propulsé par',
 'notification_you_have'               => 'Vous avez',
 'notification_notification'           => 'Notifications',
 'notification_new'                    => 'Vous avez une nouvelle notification !',
 'login_register_style'                => 'Style de registre de connexion',
 'email_setting'                       => 'Paramètres de messagerie',
 'application_setting'                 => 'Paramètres Application',

 // table filter & sort
  'filter_select_operator_type'         => 'Select Operator Type',
 'filter_ascending'                    => 'ASCENDING',
 'filter_descending'                   => 'DESCENDING',
 'filter_equal_to'                     => '=(Equal to)',
 'filter_like'                         => 'LIKE',
 'filter_not_like'                     => 'NOT LIKE',
 'filter_greater_than_or_equal'        => '>= (Greater Than or Equal)',
 'filter_less_than_or_equal'           => '<= (Less Than or Equal)',
 'filter_less_than'                    => '< (Less Than)',
 'filter_greater_than'                 => '> (Greater Than)',
 'filter_not_equal_to'                 => '!= (Not Equal to)',
 'filter_in'                           => 'IN',
 'filter_not_in'                       => 'NOT IN',
 'filter_between'                      => 'BETWEEN',
 'filter_empty_or_null'                => 'Empty ( or Null)',
 'filter_sort_ascending'               => 'Sort ascending',
 'filter_sort_descending'              => 'Sort Descending',
 'filter_eg'                           => 'e.g',
 'filter_lorem_ipsum'                  => 'Lorem ipsum',
 'filter_lorem_ipsum_dolor_sit'        => ' Lorem,Ipsum,Dolor Sit',
 'filter_search'                       => 'Search',
 'filter_from'                         => 'from',
 'filter_to'                           => 'to',
 'filter_sorting'                      => 'Sorting',
 'filter_rows_total'                   => 'Total rows',
 'filter_rows_to'                      => 'to',
 'filter_rows_of'                      => 'of',

 // confirmation
  'confirmation_yes'                    => 'Oui',
 'confirmation_no'                     => 'Non',

 //gestionnaire de fichiers
  'chose_an_image'                      => 'Choisir une image',
 'chose_an_file'                       => 'Choisissez un fichier',

 //confirmation d'action
  'confirmation_title'                  => 'Confirmation',
 'confirmation_text'                   => 'Voulez-vous vraiment effectuer cette action ?',
 'confirmButtonText'                   => 'Oui',

 // privilège
  'privileges_name'                     => 'Nom du privilège',
 'privileges_super_admin'              => 'Super Admin',
 'privileges_standart_user'            => 'Utilisateur standard',
 'privileges_ID'                       => 'ID',
 'set_as_superadmin'                   => 'Définir comme Superadmin',
 'chose_theme_color_select'            => '** Choisir la couleur du thème du backend',
 'chose_theme_color'                   => 'Couleur du thème',
 'privileges_configuration'            => 'Configuration des privilèges',
 'privileges_module_list_no'           => 'Non',
 'privileges_module_list_mod_names'    => 'Nom du module',
 'privileges_module_list_view'         => 'View',
 'privileges_module_list_create'       => 'Créer',
 'privileges_module_list_read'         => 'Read',
 'privileges_module_list_update'       => 'Update',
 'privileges_module_list_delete'       => 'Delete',

 //datamodal
  'datamodal_select'                    => 'Sélectionner',
 'datamodal_search_and_enter'          => 'Rechercher et entrer...',
 'datamodal_enter_to_search'           => 'Entrer pour rechercher',
 'datamodal_browse_data'               => 'Parcourir les données',
 'datamodal_browse_file'               => 'Parcourir Fichier',

 //child
  'table_detail'                        => 'Détail de la table',
 'your_file_size_is_too_big'           => 'La taille de votre fichier est trop grande',
 'save_changes'                        => 'Enregistrer les modifications',
 'please_complete_the_form'            => 'Veuillez remplir le formulaire !',
 'this_field_is_required'              => 'Ce champ est obligatoire',
 'text_form'                           => 'Formulaire',
 "your_file_extension_is_not_allowed " => "Votre extension de fichier n'est pas autorisée !",

];
